### ISSUE TITLE
Not working properly

### ISSUE THREAD

**Issue by chen-bowen** [magnusbakken/espn-fantasy-autopick#1]
The auto button is now just a text and unclickable
![image](https://user-images.githubusercontent.com/18410378/102807671-f3789c80-4373-11eb-9e4e-1f8536c97683.png)

**Comment by magnusbakken** [comment]
Thanks for the report. Yes, I'm aware of the problem, and it should be fixed in version 2.2.0. I pushed the updated version to the extension store yesterday, but it needs to go through a manual review before getting published.

**Comment by magnusbakken** [comment]
The new version is out now so I'll close this.

**Comment by chen-bowen** [comment]
It still doesn't work. the button looks right but when I click on it nothing is happening

**Comment by magnusbakken** [comment]
Ok, that's unfortunate. I haven't had any issues yet, but it may depend on the type of league, player statuses or things like that.

Could you try to look in the developer console? Go to the team page, press F12, check off the "Verbose" option where it says "Default levels" in the developer tools, and then press the Auto button.

![Screenshot 2020-12-23 11 13 06](https://user-images.githubusercontent.com/284189/102985799-0e801380-4510-11eb-8bab-b6c6e6c75465.png)

There should be a line saying something like "Performing auto-setup with current settings". In your case there may be some sort of red error message. If you could copy or take a screenshot of what it says and paste it here it would be very helpful. A screenshot of your team and league settings would also be great.

**Comment by KingGrind** [comment]
I am having the same issue.
![Issue](https://user-images.githubusercontent.com/62342105/103226522-529d5a80-48fa-11eb-9874-403b90925ba2.png)

**Comment by magnusbakken** [comment]
Ah, thanks for the report and screenshot. I was unaware that you could set up slots with dual positions like PF/C, SG/SF etc., so the extension doesn't recognize them. I'll work on a fix.

**Comment by magnusbakken** [comment]
Fixed in version 2.2.1. The new version has been pushed to the extension store, so it should be available within a few days.
